DROP TABLE IF EXISTS todo;

CREATE TABLE login (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE todo (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deadline DATE NOT NULL,
  done BOOLEAN NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);